import type { NextPage } from 'next';
import Head from 'next/head';
import Navbar from '../components/navbar/navbar';
import About from './about';
const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Kai&apos;s Wacky Website</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Navbar />
        <About />
      </main>
    </div>
  )
}

export default Home
