import type { NextPage } from 'next';
import Head from 'next/head';
import Link from 'next/link';
import Navbar from '../components/navbar/navbar';
const Now: NextPage = () => {
	return (
		<div>
			<Head>
				<title>Kai&apos;s Wacky Website</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main>
				<Navbar />
				<NowPage />
			</main>
		</div>
	)
}

function NowPage() {
	return (
		<div className="content pages">
			<h1> Now </h1>
			<h3> Here is what I am up to nowadays </h3>
			<ul className="now-list">
				<h3> Finishing Junior Year of High School: </h3>
				<li> I am currently at home in sweet old San Jose. </li>
				<li> Currently taking Statistics, English 11, Physics, Multimedia Arts, Spanish 3, United States History, and Physical Education. </li>
				<li> Dreaming about heading up North to University of Washington, University of Waterloo, or University of British Columbia for college. </li>
				<h3> Learning about Computers: </h3>
				<li> Studying for the CompTIA A+ exam. </li>
				<li> Volunteering for Coding Organizations like CodeDay Bay Area. </li>
				<li> Programming whatever I find interesting. </li>
				<li> Participating in Hack Club. </li>
				<h3> Entertaining Myself: </h3>
				<li> Watching a lot on my Plex Server. </li>
				<li> Playing lots of video games on my modded PS4, 3DS, or Switch. </li>
				<li> Having fun with my dog, Mocha. </li>
			</ul>
			<p> Last updated 2022-03-10 </p>
			<p> Credits to <Link href="https://nownownow.com"> Derek Sivers </Link> </p>
		</div>
	)
}

export default Now;
