import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import Navbar from "../components/navbar/navbar";
const Uses: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Kai&apos;s Wacky Website</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Navbar />
        <UsesPage />
      </main>
    </div>
  );
};

function UsesPage() {
  return (
    <div className="content pages">
      <h1> Uses </h1>
      <p> The technology and equipment I use on a daily basis </p>
      <ul className="uses-list">
        <h3> My Main Desk </h3>
        <li> M1 MacBook Air 16GB 512GB SSD </li>
      </ul>
      <p> Last updated 2022-03-11 </p>
      <p>
        Credits to{" "}
        <Link href="https://github.com/wesbos/awesome-uses/"> Wes Bos </Link>
      </p>
    </div>
  );
}

export default Uses;
